### ISSUE TITLE
Add Markdown plugin

### ISSUE THREAD

**Issue by hoangleitvn** [Roslovets-Inc/ckeditor5-build-strapi-wysiwyg#19]
I am using the strapi-plugin-ckeditor5 plugin but I would like to add [Markdown](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) plugin to get output as markdown instead of HTML. Is that possible to add that plugin as a configurable so users can turn on/off.

I have tried to update the ckeditor.js configure and add plugins configuration, but I am getting [duplicated module](Error codes - CKEditor 5 Documentation) error

**Comment by roslovets** [comment]
Thanks for idea, but I don't think that Markdown mode can be configurable after editor is built.

May be you could create special Markdown fork of this plugin.

BTW I started this project just because I needed to have content of formatted text in HTML for my site. Otherwise I would continue to stick to built-in Strapi Markdown editor.
